var searchData=
[
  ['serial_20wire_20jtag_20disables',['Serial Wire JTAG disables',['../group__afio__swj__disable.html',1,'']]],
  ['systick_20defines',['SysTick Defines',['../group__CM3__systick__defines.html',1,'']]],
  ['systick',['SysTick',['../group__CM3__systick__file.html',1,'']]],
  ['system_20control_20unit_20defines',['System Control Unit Defines',['../group__scu__defines.html',1,'']]],
  ['system_20control_20unit',['System Control Unit',['../group__scu__file.html',1,'']]],
  ['sdio',['SDIO',['../group__sdio__defines.html',1,'']]],
  ['serial_20general_20purpose_20i_2fo',['Serial General Purpose I/O',['../group__sgpio__defines.html',1,'']]],
  ['spi_20peripheral_20baud_20rates',['SPI peripheral baud rates',['../group__spi__baudrate.html',1,'']]],
  ['spi_20peripheral_20baud_20rate_20prescale_20values',['SPI peripheral baud rate prescale values',['../group__spi__br__pre.html',1,'']]],
  ['spi_20clock_20phase',['SPI clock phase',['../group__spi__cpha.html',1,'']]],
  ['spi_20clock_20polarity',['SPI clock polarity',['../group__spi__cpol.html',1,'']]],
  ['spi_20defines',['SPI Defines',['../group__spi__defines.html',1,'']]],
  ['spi_20data_20frame_20format',['SPI data frame format',['../group__spi__dff.html',1,'']]],
  ['spi',['SPI',['../group__spi__file.html',1,'']]],
  ['spi_20lsb_2fmsb_20first',['SPI lsb/msb first',['../group__spi__lsbfirst.html',1,'']]],
  ['spi_20register_20base_20address',['SPI Register base address',['../group__spi__reg__base.html',1,'']]],
  ['ssi_20register_20base_20addresses',['SSI register base addresses',['../group__ssi__base.html',1,'']]],
  ['synchronous_20serial_20interface',['Synchronous Serial Interface',['../group__ssi__defines.html',1,'']]],
  ['synchronous_20serial_20port',['Synchronous Serial Port',['../group__ssp__defines.html',1,'']]],
  ['ssp',['SSP',['../group__ssp__file.html',1,'']]],
  ['stm32f0xx',['STM32F0xx',['../group__STM32F0xx.html',1,'']]],
  ['stm32f0xx_20defines',['STM32F0xx Defines',['../group__STM32F0xx__defines.html',1,'']]],
  ['stm32f1xx',['STM32F1xx',['../group__STM32F1xx.html',1,'']]],
  ['stm32f1xx_20defines',['STM32F1xx Defines',['../group__STM32F1xx__defines.html',1,'']]],
  ['stm32f2xx',['STM32F2xx',['../group__STM32F2xx.html',1,'']]],
  ['stm32f2xx_20defines',['STM32F2xx Defines',['../group__STM32F2xx__defines.html',1,'']]],
  ['stm32f3xx',['STM32F3xx',['../group__STM32F3xx.html',1,'']]],
  ['stm32f3xx_20defines',['STM32F3xx Defines',['../group__STM32F3xx__defines.html',1,'']]],
  ['stm32f4xx',['STM32F4xx',['../group__STM32F4xx.html',1,'']]],
  ['stm32f4xx_20defines',['STM32F4xx Defines',['../group__STM32F4xx__defines.html',1,'']]],
  ['stm32l1xx',['STM32L1xx',['../group__STM32L1xx.html',1,'']]],
  ['stm32l1xx_20defines',['STM32L1xx Defines',['../group__STM32L1xx__defines.html',1,'']]],
  ['syscfg_20defines',['SYSCFG Defines',['../group__syscfg__defines.html',1,'']]],
  ['syscfg',['SYSCFG',['../group__syscfg__file.html',1,'']]],
  ['system_20control',['System Control',['../group__systemcontrol__defines.html',1,'']]],
  ['sms_20slave_20mode_20selection',['SMS Slave mode selection',['../group__tim__sms.html',1,'']]]
];
